POST {{host-api}}/authorization/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123123"
}

### 登录
POST {{host-api}}/authorization/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123123",
  "password_confirmation": "123123",
  "nickname": "admin"
}

### 注册
