POST {{host-api}}/task/f6fb549c-4c06-468b-a75e-dff136d01381/cancel
Content-Type: application/json
Authorization: JWT {{auth-token}}

{}

### 标记取消
POST {{host-api}}/task/f6fb549c-4c06-468b-a75e-dff136d01381/fail
Content-Type: application/json
Authorization: JWT {{auth-token}}

{}

### 标记失败
POST {{host-api}}/task/f6fb549c-4c06-468b-a75e-dff136d01381/finish
Content-Type: application/json
Authorization: JWT {{auth-token}}

{}

### 标记完成
POST {{host-api}}/task/f6fb549c-4c06-468b-a75e-dff136d01381/process
Content-Type: application/json
Authorization: JWT {{auth-token}}

{}

### 标记执行
POST {{host-api}}/task
Content-Type: application/json
Authorization: JWT {{auth-token}}

{
  "name": "测试任务A",
  "targets": [
    "B074C01"
  ],
  "content": "{\"name\":\"张三\"}",
  "business_type": "equipmentKinds"
}

### 新建
POST {{host-api}}/task/452670af-d492-4aba-a073-22518b6d462c/detail
Content-Type: application/json
Authorization: JWT {{auth-token}}

{
  "preloads": [
    "ContentFile"
  ]
}

### 详情
POST {{host-api}}/task/list
Content-Type: application/json
Authorization: JWT {{auth-token}}

{
  "preloads": [
    "ContentFile"
  ]
}

### 列表
